server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
spring:
  application:
    name: discovery-server