server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: product-service
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  type-aliases-package: com.programmingtechie.productservice.models

logging:
  level:
    com.programmingtechie.productservice.repositories.mybatis: trace

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  sql:
    init:
      mode: always